import { createContext, useCallback, useContext, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'
import { ApiError, api } from './api'
import type { Leave, User } from './api'

type Route = '/signup' | '/login' | '/dashboard' | '/leave'
const navItems: { label: string; route: Route }[] = [{ label: 'Dashboard', route: '/dashboard' }, { label: 'Profile', route: '/dashboard' }, { label: 'Attendance', route: '/dashboard' }, { label: 'Leave', route: '/leave' }, { label: 'Payroll', route: '/dashboard' }]
function go(route: Route) { window.history.pushState({}, '', route); window.dispatchEvent(new PopStateEvent('popstate')) }

type ToastKind = 'success' | 'error' | 'warning' | 'info'
type Toast = { title: string; description: string; kind: ToastKind }
const ToastContext = createContext<(toast: Toast) => void>(() => undefined)
const useToast = () => useContext(ToastContext)

function describeError(error: unknown): Toast {
  const status = error instanceof ApiError ? error.status : null
  const detail = error instanceof ApiError ? error.message : ''
  const knownValidationMessages = new Set(['Employee ID, email, and password are required', 'Enter a valid email address', 'Password must be at least 8 characters', 'Start date, end date, and reason are required', 'End date cannot be before start date'])
  if (status === 400) return { kind: 'warning', title: 'Check your request', description: knownValidationMessages.has(detail) ? detail : 'Some of the information is invalid. Review the fields and try again.' }
  if (status === 401) return { kind: 'error', title: 'Sign-in required', description: 'Your sign-in details are invalid or your session has expired. Please sign in again.' }
  if (status === 403) return { kind: 'error', title: 'Permission denied', description: 'You do not have permission to perform this action. Contact an administrator if you need access.' }
  if (status === 404) return { kind: 'error', title: 'Not found', description: 'The requested Dayflow resource could not be found. Return to the dashboard and try again.' }
  if (status === 409) return { kind: 'warning', title: 'Account already exists', description: detail === 'An account with this email already exists' ? detail : 'This action conflicts with an existing record. Check the details and try again.' }
  if (status === 413) return { kind: 'warning', title: 'Request too large', description: 'The submitted request is too large. Remove some content and try again.' }
  if (status === 429) return { kind: 'warning', title: 'Please wait a moment', description: 'You are making requests too quickly. Wait a moment before trying again.' }
  if (status === 500) return { kind: 'error', title: 'Server error', description: 'An unexpected server error occurred. Please try again.' }
  if (status === 502) return { kind: 'error', title: 'Dependent service unavailable', description: 'A service Dayflow relies on failed to respond. Please try again later.' }
  if (status === 503) return { kind: 'error', title: 'Service temporarily unavailable', description: 'Dayflow is temporarily unavailable. Please try again later.' }
  return { kind: 'error', title: 'Connection problem', description: 'Dayflow could not be reached. Check your connection and try again.' }
}

function ToastViewport({ toast, onDismiss }: { toast: Toast | null; onDismiss: () => void }) {
  if (!toast) return null
  return <div className={`toast toast-${toast.kind}`} role="alert"><div><strong>{toast.title}</strong><p>{toast.description}</p></div><button type="button" aria-label="Dismiss notification" onClick={onDismiss}>×</button></div>
}

function ToastProvider({ children }: { children: React.ReactNode }) {
  const [toast, setToast] = useState<Toast | null>(null)
  useEffect(() => { if (!toast) return undefined; const timer = window.setTimeout(() => setToast(null), 6000); return () => window.clearTimeout(timer) }, [toast])
  return <ToastContext.Provider value={setToast}><ToastViewport toast={toast} onDismiss={() => setToast(null)} />{children}</ToastContext.Provider>
}

function AuthCard({ mode, onAuthenticated }: { mode: 'login' | 'signup'; onAuthenticated: (token: string, user: User) => void }) {
  const [employeeId, setEmployeeId] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [showPassword, setShowPassword] = useState(false); const isSignup = mode === 'signup'
  const showToast = useToast()
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setLoading(true); try { const result = isSignup ? await api.signup({ employeeId, email, password }) : await api.login({ email, password }); showToast({ kind: 'success', title: isSignup ? 'Account created' : 'Signed in', description: isSignup ? 'Your Dayflow account is ready.' : 'Welcome back to Dayflow.' }); onAuthenticated(result.token, result.user) } catch (err) { const toast = describeError(err); setError(toast.description); showToast(toast) } finally { setLoading(false) } }
  return <main className={`auth-page ${isSignup ? 'auth-page-signup' : 'auth-page-login'}`}>{!isSignup && <section className="auth-brand-panel" aria-label="Dayflow introduction"><div><div className="brand-mark brand-mark-light">DAYFLOW</div><p className="brand-tagline">Every workday,<br /><em>perfectly aligned.</em></p></div><div className="brand-panel-footer"><span className="brand-rule" /> <span>Employee workspace</span></div></section>}<section className="auth-card"><div className="mobile-brand"><div className="brand-mark">DAYFLOW</div><p className="eyebrow">Every workday, perfectly aligned.</p></div><div className="auth-heading"><p className="eyebrow">{isSignup ? 'Employee access' : 'Employee workspace'}</p><h1>{isSignup ? 'Create your account' : 'Welcome Back'}</h1><p className="auth-copy">{isSignup ? 'Set up your employee access to get started.' : 'Sign in to continue to your Dayflow workspace.'}</p></div><form onSubmit={submit} className="auth-form">{isSignup && <label>Employee ID<input value={employeeId} onChange={(event) => setEmployeeId(event.target.value)} placeholder="e.g. EMP-1024" autoComplete="username" required /></label>}<label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@company.com" autoComplete="email" required /></label><label>Password<div className="password-field"><input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" autoComplete={isSignup ? 'new-password' : 'current-password'} minLength={8} required /><button type="button" className="password-toggle" onClick={() => setShowPassword((visible) => !visible)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 3l18 18M10.6 10.6a2 2 0 0 0 2.8 2.8M9.9 5.2A10.8 10.8 0 0 1 12 5c5.2 0 8.7 4.4 10 7a14.8 14.8 0 0 1-3 3.8M6.2 6.2C4.5 7.4 3.3 9.2 2 12c1.3 2.6 4.8 7 10 7 1 0 1.9-.2 2.7-.5" /></svg> : <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7S2 12 2 12Z" /><circle cx="12" cy="12" r="2.5" /></svg>}</button></div></label>{!isSignup && <span className="forgot-link">Forgot Password?</span>}{error && <p className="form-error">{error}</p>}<button className="primary-button auth-submit" disabled={loading}>{loading ? 'Please wait…' : isSignup ? 'Sign Up' : 'Sign In'}<span aria-hidden="true">→</span></button></form><p className="auth-switch">{isSignup ? 'Already have an account?' : "Don't have an account?"} <button type="button" onClick={() => go(isSignup ? '/login' : '/signup')}>{isSignup ? 'Sign In' : 'Sign Up'}</button></p></section></main>
}

function Shell({ user, children, active }: { user: User; children: React.ReactNode; active: Route }) {
  return <div className="min-h-screen bg-dayflow-bg text-dayflow-ink"><div className="mx-auto flex max-w-7xl"><aside className="hidden w-72 shrink-0 bg-dayflow-ink p-6 text-dayflow-soft md:flex md:flex-col"><div className="mb-10"><div className="text-2xl font-semibold tracking-[0.2em] text-dayflow-cream">DAYFLOW</div></div><nav className="space-y-2">{navItems.map((item) => <button key={item.label} type="button" onClick={() => go(item.route)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm transition ${active === item.route && item.label !== 'Profile' && item.label !== 'Attendance' && item.label !== 'Payroll' ? 'bg-dayflow-primary text-white shadow-sm' : 'text-dayflow-subtle hover:bg-dayflow-muted hover:text-dayflow-ink'}`}><span className="inline-flex h-2.5 w-2.5 rounded-full bg-current opacity-80" />{item.label}</button>)}</nav><div className="mt-auto space-y-2 border-t border-white/10 pt-6"><p className="px-4 text-xs text-dayflow-subtle">{user.email}</p><button type="button" onClick={() => { localStorage.removeItem('dayflow_token'); go('/login') }} className="block w-full rounded-xl px-4 py-3 text-left text-sm text-dayflow-subtle hover:bg-dayflow-muted/10">Logout</button></div></aside><main className="flex-1 p-6 lg:p-10">{children}</main></div></div>
}

function LeaveHistory({ leaves, loading, error }: { leaves: Leave[]; loading: boolean; error: string }) {
  return <section className="leave-history rounded-2xl border border-dayflow-border bg-white p-6 shadow-sm"><div className="section-heading"><div><p className="eyebrow">Your requests</p><h2>Leave history</h2></div><button className="secondary-button" onClick={() => go('/leave')}>Apply for leave <span>→</span></button></div>{loading && <p className="muted-text">Loading your leave requests…</p>}{error && <p className="form-error">{error}</p>}{!loading && !error && leaves.length === 0 && <p className="muted-text">No leave applications yet. Your submitted requests will appear here.</p>}{leaves.length > 0 && <div className="leave-list">{leaves.map((leave) => <article className="leave-row" key={leave.id}><div><strong>{leave.leaveType} leave</strong><p>{leave.startDate} → {leave.endDate}</p><small>{leave.reason}</small></div><span className={`status status-${leave.status}`}>{leave.status}</span></article>)}</div>}</section>
}

function Dashboard({ user }: { user: User }) {
  const [leaves, setLeaves] = useState<Leave[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const showToast = useToast()
  useEffect(() => { api.leaves().then((result) => setLeaves(result.leaves)).catch((err) => { const toast = describeError(err); setError(toast.description); showToast(toast) }).finally(() => setLoading(false)) }, [showToast])
  const summaryCards = [{ label: 'Present Days', value: '24', detail: '+3 from last month' }, { label: 'Leave Balance', value: '12', detail: `${leaves.filter((leave) => leave.status === 'pending').length} pending approval` }, { label: 'Net Pay', value: '₹42,800', detail: 'Updated today' }]
  return <Shell user={user} active="/dashboard"><header className="mb-8 flex flex-col gap-4 border-b border-dayflow-border pb-6 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-dayflow-secondary">Employee Portal</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-dayflow-ink md:text-4xl">Dashboard</h1><p className="mt-2 text-dayflow-secondary">Good to see you, {user.employeeId}.</p></div><div className="rounded-2xl border border-dayflow-border bg-white px-4 py-3 shadow-sm"><p className="text-xs uppercase tracking-[0.2em] text-dayflow-secondary">Today</p><p className="mt-1 text-sm font-medium text-dayflow-ink">{new Date().toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })}</p></div></header><section className="grid gap-4 md:grid-cols-3">{summaryCards.map((card) => <article key={card.label} className="rounded-2xl border border-dayflow-border bg-white p-5 shadow-sm"><p className="text-sm text-dayflow-secondary">{card.label}</p><div className="mt-3 text-3xl font-semibold text-dayflow-ink">{card.value}</div><p className="mt-2 text-sm text-dayflow-secondary">{card.detail}</p></article>)}</section><section className="mt-8 grid gap-6 lg:grid-cols-[1.5fr_0.9fr]"><div className="rounded-2xl border border-dayflow-border bg-white p-6 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold text-dayflow-ink">Attendance Overview</h2><span className="rounded-full bg-dayflow-accent/10 px-2.5 py-1 text-xs font-medium text-dayflow-accent">On Track</span></div><div className="h-48 rounded-xl bg-gradient-to-r from-dayflow-primary/10 via-dayflow-accent/20 to-dayflow-muted/20 p-4"><div className="flex h-full items-end gap-3">{[32, 46, 58, 76, 72, 85, 92].map((height, index) => <div key={index} className="flex-1 rounded-t-xl bg-dayflow-primary/70" style={{ height: `${height}%` }} />)}</div></div></div><div className="rounded-2xl border border-dayflow-border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-dayflow-ink">Quick Actions</h2><div className="mt-5 space-y-3"><button type="button" onClick={() => go('/leave')} className="flex w-full items-center justify-between rounded-xl bg-dayflow-primary px-4 py-3 text-sm font-medium text-white transition hover:bg-dayflow-primary/90">Request Leave <span>→</span></button><button type="button" className="flex w-full items-center justify-between rounded-xl border border-dayflow-border px-4 py-3 text-sm font-medium text-dayflow-ink transition hover:bg-dayflow-bg">View Payslip <span>→</span></button><button type="button" className="flex w-full items-center justify-between rounded-xl border border-dayflow-border px-4 py-3 text-sm font-medium text-dayflow-ink transition hover:bg-dayflow-bg">Check Attendance <span>→</span></button></div></div></section><LeaveHistory leaves={leaves} loading={loading} error={error} /></Shell>
}

function LeavePage({ user }: { user: User }) {
  const [form, setForm] = useState({ startDate: '', endDate: '', leaveType: 'Casual', reason: '' }); const [leaves, setLeaves] = useState<Leave[]>([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const showToast = useToast()
  const loadLeaves = useCallback(() => api.leaves().then((result) => setLeaves(result.leaves)).catch((err) => { const toast = describeError(err); setError(toast.description); showToast(toast) }), [showToast])
  useEffect(() => { void loadLeaves() }, [loadLeaves])
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); setMessage(''); try { await api.createLeave(form); setForm({ startDate: '', endDate: '', leaveType: 'Casual', reason: '' }); setMessage('Leave application submitted and is now pending approval.'); showToast({ kind: 'success', title: 'Leave submitted', description: 'Your request is pending admin approval.' }); await loadLeaves() } catch (err) { const toast = describeError(err); setError(toast.description); showToast(toast) } finally { setLoading(false) } }
  return <Shell user={user} active="/leave"><header className="mb-8 border-b border-dayflow-border pb-6"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-dayflow-secondary">Employee Portal</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-dayflow-ink md:text-4xl">Leave Application</h1><p className="mt-2 text-dayflow-secondary">Request time away and track the approval status here.</p></header><div className="leave-layout"><section className="rounded-2xl border border-dayflow-border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-dayflow-ink">New request</h2><form className="leave-form" onSubmit={submit}><label>Leave type<select value={form.leaveType} onChange={(event) => setForm({ ...form, leaveType: event.target.value })}><option>Casual</option><option>Sick</option><option>Emergency</option><option>Annual</option></select></label><div className="date-grid"><label>Start date<input type="date" value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} required /></label><label>End date<input type="date" value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} required /></label></div><label>Reason<textarea value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} placeholder="Tell your manager why you need leave" rows={4} required /></label>{message && <p className="form-success">{message}</p>}{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={loading}>{loading ? 'Submitting…' : 'Submit application'}</button></form></section><section className="rounded-2xl border border-dayflow-border bg-white p-6 shadow-sm"><p className="eyebrow">Status</p><h2 className="text-xl font-semibold text-dayflow-ink">Your applications</h2><div className="leave-list mt-5">{leaves.length === 0 ? <p className="muted-text">Your applications will appear here.</p> : leaves.map((leave) => <article className="leave-row" key={leave.id}><div><strong>{leave.leaveType} leave</strong><p>{leave.startDate} → {leave.endDate}</p></div><span className={`status status-${leave.status}`}>{leave.status}</span></article>)}</div></section></div></Shell>
}

function AppContent() {
  const [route, setRoute] = useState<Route>((window.location.pathname as Route) || '/login'); const [user, setUser] = useState<User | null>(null); const [checking, setChecking] = useState(() => Boolean(localStorage.getItem('dayflow_token')))
  const showToast = useToast()
  useEffect(() => { const onPopState = () => setRoute((window.location.pathname as Route) || '/login'); window.addEventListener('popstate', onPopState); if (localStorage.getItem('dayflow_token')) api.me().then((result) => setUser(result.user)).catch((err) => { localStorage.removeItem('dayflow_token'); if (err instanceof ApiError && err.status === 401) showToast(describeError(err)) }).finally(() => setChecking(false)); return () => window.removeEventListener('popstate', onPopState) }, [showToast])
  const authenticated = (token: string, nextUser: User) => { localStorage.setItem('dayflow_token', token); setUser(nextUser); go('/dashboard') }
  if (checking) return <div className="loading-screen">Loading Dayflow…</div>
  if (!user && (route === '/dashboard' || route === '/leave')) { go('/login'); return null }
  if (user && (route === '/login' || route === '/signup')) { go('/dashboard'); return null }
  if (route === '/signup') return <AuthCard mode="signup" onAuthenticated={authenticated} />
  if (route === '/leave') return <LeavePage user={user!} />
  if (route === '/dashboard') return <Dashboard user={user!} />
  return <AuthCard mode="login" onAuthenticated={authenticated} />
}

function App() {
  return <ToastProvider><AppContent /></ToastProvider>
}

export default App
