"use client";

import Link from "next/link";
import { ArrowLeft, Check, Clock3, LogIn, LogOut } from "lucide-react";
import { useState } from "react";
import { EmployeeFeedback } from "../_components/employee-feedback";

type AttendanceRow = { date: string; checkIn: string | null; checkOut: string | null; status: "Present" | "Absent" | "Leave" };
const initialRows: AttendanceRow[] = [
  { date: "Monday, 18 August", checkIn: "09:02 AM", checkOut: "05:31 PM", status: "Present" },
  { date: "Tuesday, 19 August", checkIn: "09:11 AM", checkOut: "05:04 PM", status: "Present" },
  { date: "Wednesday, 20 August", checkIn: null, checkOut: null, status: "Leave" },
  { date: "Thursday, 21 August", checkIn: "09:00 AM", checkOut: "05:18 PM", status: "Present" },
];

export default function EmployeeAttendancePage() {
  const [view, setView] = useState<"Daily" | "Weekly">("Weekly");
  const [rows, setRows] = useState(initialRows);
  const [error, setError] = useState("");
  const today = rows[rows.length - 1];

  function currentTime() { return new Date().toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" }); }
  function checkIn() { if (today.checkIn) { setError("You are already checked in for today."); return; } setRows((current) => current.map((row, index) => index === current.length - 1 ? { ...row, checkIn: currentTime(), status: "Present" } : row)); }
  function checkOut() { if (!today.checkIn) { setError("You must check in before checking out."); return; } if (today.checkOut) { setError("You are already checked out for today."); return; } setRows((current) => current.map((row, index) => index === current.length - 1 ? { ...row, checkOut: currentTime() } : row)); }

  return <main className="min-h-screen bg-[#f7f6f1] px-4 py-6 text-[#534332] sm:px-8 lg:px-12">{error && <EmployeeFeedback message={error} onDismiss={() => setError("")} />}<div className="mx-auto max-w-6xl"><Link href="/employee/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-[#454f2d] hover:text-[#9f7e4a]"><ArrowLeft className="h-4 w-4" /> Back to dashboard</Link><header className="mt-6 border-b border-[#ded9cf] pb-7"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#797f3e]">Employee record</p><h1 className="mt-2 text-3xl font-bold text-[#394032]">Attendance</h1><p className="mt-2 text-[#6d6a61]">Your attendance history, visible only to you.</p></header>
    <section className="mt-8 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><div className="rounded-xl border border-[#ded9cf] bg-[#394032] p-6 text-white shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#e2c58e]">Today</p><h2 className="mt-2 text-2xl font-bold">{today.status}</h2></div><span className="rounded-full bg-white/10 p-3 text-[#e2c58e]"><Check className="h-6 w-6" /></span></div><div className="mt-7 grid grid-cols-2 gap-3"><button onClick={checkIn} disabled={Boolean(today.checkIn)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#e2c58e] px-3 py-2.5 text-sm font-bold text-[#394032] disabled:cursor-not-allowed disabled:opacity-50"><LogIn className="h-4 w-4" /> Check in</button><button onClick={checkOut} disabled={!today.checkIn || Boolean(today.checkOut)} className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/30 px-3 py-2.5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><LogOut className="h-4 w-4" /> Check out</button></div><div className="mt-6 flex justify-between border-t border-white/15 pt-4 text-sm text-white/75"><span>In: {today.checkIn ?? "Not recorded"}</span><span>Out: {today.checkOut ?? "Not recorded"}</span></div></div><div className="rounded-xl border border-[#ded9cf] bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#797f3e]">Overview</p><h2 className="mt-2 text-xl font-bold text-[#394032]">This week</h2></div><Clock3 className="h-5 w-5 text-[#9f7e4a]" /></div><div className="mt-6 grid grid-cols-3 gap-3"><Stat label="Present" value="3" /><Stat label="Leave" value="1" /><Stat label="Hours" value="24h 42m" /></div></div></section>
    <section className="mt-6 rounded-xl border border-[#ded9cf] bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#797f3e]">History</p><h2 className="mt-2 text-xl font-bold text-[#394032]">Attendance records</h2></div><div className="flex rounded-lg border border-[#ded9cf] p-1">{(["Daily", "Weekly"] as const).map((option) => <button key={option} onClick={() => setView(option)} className={`rounded-md px-4 py-2 text-sm font-semibold ${view === option ? "bg-[#454f2d] text-white" : "text-[#6d6a61] hover:bg-[#eef0e4]"}`}>{option}</button>)}</div></div>{view === "Daily" ? <p className="mt-6 rounded-lg bg-[#f7f6f1] p-4 text-sm text-[#6d6a61]">Daily view is focused on today&apos;s check-in and check-out controls above.</p> : <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="border-b border-[#ded9cf] text-xs uppercase tracking-wide text-[#6d6a61]"><tr><th className="pb-3">Date</th><th className="pb-3">Check in</th><th className="pb-3">Check out</th><th className="pb-3">Working hours</th><th className="pb-3">Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.date} className="border-b border-[#ded9cf] last:border-0"><td className="py-4 font-semibold">{row.date}</td><td className="py-4">{row.checkIn ?? "-"}</td><td className="py-4">{row.checkOut ?? "-"}</td><td className="py-4">{workingHours(row.checkIn, row.checkOut)}</td><td className="py-4"><Status status={row.status} /></td></tr>)}</tbody></table></div>}</section></div></main>;
}
function workingHours(checkIn: string | null, checkOut: string | null) { return checkIn && checkOut ? "8h 30m" : "-"; }
function Status({ status }: { status: AttendanceRow["status"] }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${status === "Present" ? "bg-[#eef0e4] text-[#454f2d]" : status === "Leave" ? "bg-[#f1eee7] text-[#9f7e4a]" : "bg-[#f7e9e3] text-[#8b5b48]"}`}>{status}</span>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-[#f7f6f1] p-3"><p className="text-xs text-[#6d6a61]">{label}</p><p className="mt-1 text-lg font-bold text-[#394032]">{value}</p></div>; }